title   AI Arch Linux (x86_64, UEFI) - Debug
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% rootdelay=15 nvidia_drm.modeset=1 cow_spacesize=30G amd_pstate=active plymouth.enable=0 systemd.log_level=info
