title   AI Arch Linux (x86_64, UEFI) - Safe Mode (no AI daemon)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% rootdelay=5 rd.udev.children-max=16 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 amd_pstate=active mitigations=auto nowatchdog cow_spacesize=30G quiet loglevel=3 splash systemd.show_status=auto ai.mode=safe
