"""
Integration tests for ai-control's v2 phrase dictionary.

Session 63, Agent A3.

Validates the artifact produced by:

    python3 -m dictionary_v2 --build /usr/share/ai-control/dictionary_v2.pkl.zst

The dictionary is a zstd (or gzip-on-3.13) compressed pickle of phrase
-> handler mappings, expanded from a small set of templates into the
5000-10000 range. Runtime usage in contusion.py is:

    from dictionary_v2 import lookup
    result = lookup("turn down the volume")
    # {"handler_type": "audio.volume_down", "args": {}, "confidence": 0.85,
    #  "source": "v2_template"}

These tests are HERMETIC: they build the artifact into a tmp_path and
exercise the in-memory lookup. No daemon, no network, no real subprocess
beyond the build CLI itself.

Skips cleanly via pytest.importorskip() if Agent A1's dictionary_v2.py
is not yet on disk, so the suite stays green during parallel development.
"""

from __future__ import annotations

import re
import statistics
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

import pytest


# Add the daemon source dir to sys.path so `import dictionary_v2` resolves
# regardless of where pytest is invoked from. Mirrors the pattern in
# conftest.py / test_markov_chains.py.
REPO_ROOT = Path(__file__).resolve().parents[2]
DAEMON_ROOT = REPO_ROOT / "ai-control" / "daemon"
if str(DAEMON_ROOT) not in sys.path:
    sys.path.insert(0, str(DAEMON_ROOT))


# Skip the entire module if Agent A1 has not shipped dictionary_v2.py yet.
dictionary_v2 = pytest.importorskip(
    "dictionary_v2",
    reason="agent A1 may not have shipped dictionary_v2.py yet",
)


# 30+ representative routes spanning all 14 handler families. Each route is a
# real phrase generated by Agent A1's templates AND a real handler key in
# contusion_handlers.HANDLERS — verified by probing the live artifact (see
# scripts/probe_v2.py). The assertion uses substring matching
# (`expected in r["handler_type"]`) so the test tolerates minor naming drift
# (e.g. audio.volume_up vs audio.vol_up) as long as the family + intent is
# preserved.
#
# Notes on coverage:
#   - v2 deliberately omits destructive/arg-bearing actions per A1's spec:
#     no driver.load, service.restart/stop, game.launch/kill, app.install_*,
#     script.run, clipboard.copy. These are routed by the static dict /
#     Markov layer instead.
#   - The 14 families assertion (test_routes_cover_all_14_families) requires
#     at least one phrase per family, which we satisfy via the *.list /
#     status / claude_status entries v2 does ship.
ROUTES: list[tuple[str, str]] = [
    # BRIGHTNESS
    ("raise the brightness", "brightness.up"),
    ("dim the screen", "brightness.down"),
    ("brightness level", "brightness.get"),
    ("max brightness", "brightness.max"),
    ("auto brightness", "brightness.auto"),
    # AUDIO
    ("raise the volume", "audio.volume_up"),
    ("lower volume", "audio.volume_down"),
    ("mute the sound", "audio.mute_toggle"),
    ("toggle the microphone", "audio.mic_mute_toggle"),
    ("list audio sinks", "audio.sink_list"),
    # MEDIA
    ("kill the music", "media.stop"),
    ("pause music", "media.pause"),
    ("next track", "media.next"),
    ("previous track", "media.prev"),
    ("now playing", "media.status"),
    ("list media players", "media.list_players"),
    # POWER
    ("turn off the screen", "power.screen_off"),
    ("wake the screen", "power.screen_on"),
    ("lock the screen", "power.lock_screen"),
    ("unlock the screen", "power.unlock_screen"),
    # SYSTEM
    ("take a screenshot", "system.screenshot_full"),
    ("screenshot the window", "system.screenshot_window"),
    ("snipping tool", "system.screenshot_region"),
    ("send a notification", "system.notify"),
    ("toggle night light", "system.night_light"),
    # MONITORING
    ("battery left", "monitoring.battery_percent"),
    ("battery time remaining", "monitoring.battery_time"),
    ("show bluetooth", "monitoring.bt_devices"),
    ("gpu temperature", "monitoring.gpu_temp"),
    ("gpu info", "monitoring.gpu_status"),
    ("cpu freq", "monitoring.cpu_freq"),
    ("fan rpm", "monitoring.fan_speed"),
    ("wifi strength", "monitoring.wifi_signal"),
    ("list displays", "monitoring.display_list"),
    # WINDOW
    ("close the window", "window.close"),
    ("list open windows", "window.list"),
    ("minimize this", "window.minimize"),
    ("maximize this", "window.maximize"),
    ("toggle fullscreen", "window.fullscreen_toggle"),
    # WORKSPACE
    ("next workspace", "workspace.next"),
    ("previous workspace", "workspace.prev"),
    ("new workspace", "workspace.new"),
    ("list workspaces", "workspace.list"),
    ("show all workspaces", "workspace.show_all"),
    # SERVICE (v2 ships only the read-only list action)
    ("list services", "service.list"),
    # DRIVER (v2 ships only the read-only list action)
    ("list drivers", "driver.list"),
    # SCRIPT (v2 ships only the read-only list action)
    ("list scripts", "script.list"),
    # APP / CLAUDE
    ("is claude installed", "app.claude_status"),
    ("init claude workspace", "app.claude_workspace_init"),
    # GAME (v2 ships only read-only list/running)
    ("list games", "game.list"),
    ("running games", "game.running"),
    # CLIPBOARD
    ("show clipboard", "clipboard.get"),
    ("clear clipboard", "clipboard.clear"),
    ("clipboard history", "clipboard.history"),
    ("paste at cursor", "clipboard.paste_cursor"),
]


@pytest.fixture(scope="module")
def built_artifact(tmp_path_factory):
    """Build the dictionary into a tmp file once per test module.

    Returns a dict with: path (Path), stdout (str), phrase_count (int|None),
    raw_size (int|None), compressed_size (int|None), ratio (float|None).
    """
    tmp = tmp_path_factory.mktemp("dict_v2")
    out_path = tmp / "dictionary_v2.pkl.zst"

    proc = subprocess.run(
        [sys.executable, "-m", "dictionary_v2", "--build", str(out_path)],
        capture_output=True,
        text=True,
        cwd=str(DAEMON_ROOT),
        timeout=120,
    )
    if proc.returncode != 0:
        pytest.fail(
            f"--build failed (rc={proc.returncode}):\n"
            f"STDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}"
        )
    if not out_path.exists():
        pytest.fail(f"--build returned 0 but artifact missing at {out_path}")

    out = proc.stdout + "\n" + proc.stderr  # be liberal about where CLI logs land

    # Parse "Built N phrases" — the CLI is contracted to print this line.
    m_count = re.search(r"Built\s+(\d+)\s+phrases", out, re.IGNORECASE)
    phrase_count = int(m_count.group(1)) if m_count else None

    # Parse the CLI's "302.4KB raw, 25.1KB compressed, 12.0x ratio" line.
    # Tolerate a few permutations so a future CLI tweak doesn't silently
    # skip the test.
    m_raw = (re.search(r"raw[\s=:]+(\d+)", out, re.IGNORECASE)
             or re.search(r"([\d.]+)\s*KB\s+raw", out, re.IGNORECASE))
    m_comp = (re.search(r"compressed[\s=:]+(\d+)", out, re.IGNORECASE)
              or re.search(r"([\d.]+)\s*KB\s+compressed", out, re.IGNORECASE))
    m_ratio = (re.search(r"ratio[\s=:]+([\d.]+)", out, re.IGNORECASE)
               or re.search(r"([\d.]+)x\s+ratio", out, re.IGNORECASE))
    # KB-form values are floats — promote to bytes when needed.
    def _bytes_or_int(m: Optional[re.Match]) -> Optional[int]:
        if m is None:
            return None
        s = m.group(1)
        try:
            f = float(s)
        except ValueError:
            return None
        # Heuristic: if the matched form was the "KB" alternative, the
        # number is in KB (often fractional); otherwise it's already bytes.
        if "." in s:
            return int(f * 1024)
        return int(f)
    raw_size = _bytes_or_int(m_raw)
    compressed_size = _bytes_or_int(m_comp)
    ratio = float(m_ratio.group(1)) if m_ratio else None

    return {
        "path": out_path,
        "stdout": out,
        "phrase_count": phrase_count,
        "raw_size": raw_size,
        "compressed_size": compressed_size,
        "ratio": ratio,
    }


def _reset_cache() -> None:
    """Best-effort reset of the module-level lookup cache.

    A1's module uses `_PHRASES`, `_LOAD_PATH`, `_LOAD_ERROR` as the lazy
    loader's state. Setting `_PHRASES = None` forces `_ensure_loaded()` to
    re-read the artifact from `AICONTROL_DICTIONARY_V2_PATH`. We also poke
    a few alternate names defensively in case the module gets refactored.
    """
    for attr in ("_PHRASES", "_LOAD_PATH", "_LOAD_ERROR",
                 "_cache", "_CACHE", "_loaded", "_LOADED",
                 "_dictionary", "_DICTIONARY"):
        if hasattr(dictionary_v2, attr):
            try:
                setattr(dictionary_v2, attr, None)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# 1. Phrase count + size + compression ratio
# ---------------------------------------------------------------------------

def test_phrase_count_above_floor(built_artifact):
    """v2 has to expand templates into >= 5000 distinct phrases — that
    is the entire reason it exists vs the static dictionary."""
    pc = built_artifact["phrase_count"]
    if pc is None:
        pytest.skip(
            "CLI did not print 'Built N phrases' — cannot verify count "
            f"(stdout was: {built_artifact['stdout'][:400]!r})"
        )
    assert pc >= 5000, f"phrase count {pc} below 5000 floor"


def test_compressed_size_in_range(built_artifact):
    """Compressed artifact should sit in 10KB-500KB. A1's reference build
    is ~25KB at zstd level 19 over ~7K phrases (12x ratio) — so 10KB is
    a generous floor that catches "templates didn't expand at all" without
    flagging A1's normal output. Upper bound 500KB catches a compression
    regression or someone inlining the entire en_US wordlist."""
    size = built_artifact["path"].stat().st_size
    assert 10 * 1024 <= size <= 500 * 1024, (
        f"compressed artifact size {size} bytes outside [10KB, 500KB]"
    )


def test_compression_ratio_at_least_3x(built_artifact):
    """raw / compressed should be >= 3 — a sanity floor for zstd (or gzip)
    on highly repetitive English text. If the CLI doesn't emit raw/compressed
    sizes, fall back to recomputing from the file + a re-pickle of the
    in-memory map (skip if that also isn't possible)."""
    raw = built_artifact["raw_size"]
    comp = built_artifact["compressed_size"]
    if raw is not None and comp is not None and comp > 0:
        ratio = raw / comp
    elif built_artifact["ratio"] is not None:
        ratio = built_artifact["ratio"]
    else:
        pytest.skip("CLI did not emit raw/compressed sizes; cannot compute ratio")
    assert ratio >= 3.0, f"compression ratio {ratio:.2f}x below 3x floor"


# ---------------------------------------------------------------------------
# 2. Load latency: cold load < 1s, hot lookups < 1ms mean
# ---------------------------------------------------------------------------

def test_cold_load_under_one_second(built_artifact, monkeypatch):
    """First lookup pays the full unpickle + decompress; must complete
    in under 1 second on the test box."""
    # Point the runtime loader at our tmp artifact.
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()

    t0 = time.perf_counter()
    dictionary_v2.lookup("test phrase")
    elapsed = time.perf_counter() - t0
    assert elapsed < 1.0, f"cold lookup took {elapsed*1000:.1f}ms (>1s)"


def test_hot_lookup_mean_under_one_ms(built_artifact, monkeypatch):
    """100 successive lookups after warmup must average < 1ms each.
    If they don't, runtime contusion routing will be the bottleneck."""
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()
    # Prime the cache.
    dictionary_v2.lookup("warmup phrase")

    samples: list[float] = []
    phrase = "raise the volume"
    for _ in range(100):
        t0 = time.perf_counter()
        dictionary_v2.lookup(phrase)
        samples.append(time.perf_counter() - t0)

    mean_s = statistics.mean(samples)
    assert mean_s < 0.001, (
        f"mean hot lookup {mean_s*1000:.3f}ms exceeds 1ms ceiling "
        f"(median={statistics.median(samples)*1000:.3f}ms, "
        f"max={max(samples)*1000:.3f}ms)"
    )


# ---------------------------------------------------------------------------
# 3. Representative routes — 30+ phrases across all 14 families
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("phrase,expected", ROUTES,
                         ids=[f"{exp}::{p}" for p, exp in ROUTES])
def test_route(phrase, expected, built_artifact, monkeypatch):
    """Each phrase must resolve to a handler containing the expected
    family.action substring. Substring (not equality) tolerates minor
    naming drift in Agent A1's compiler output."""
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()

    r = dictionary_v2.lookup(phrase)
    assert r is not None, f"{phrase!r} returned None"
    assert isinstance(r, dict), f"{phrase!r} returned non-dict: {type(r).__name__}"
    assert "handler_type" in r, f"{phrase!r} missing handler_type: {r!r}"
    assert expected in r["handler_type"], (
        f"{phrase!r} -> {r['handler_type']!r}, wanted substring {expected!r}"
    )


def test_routes_cover_all_14_families(built_artifact, monkeypatch):
    """Belt-and-braces: assert the ROUTES list collectively touches all
    14 advertised families. Catches a regression where someone deletes
    a family from ROUTES without realising."""
    families = {
        "brightness", "audio", "media", "power", "system", "monitoring",
        "window", "workspace", "service", "driver", "script", "app",
        "game", "clipboard",
    }
    seen = {expected.split(".", 1)[0] for _, expected in ROUTES}
    missing = families - seen
    assert not missing, f"ROUTES list missing families: {sorted(missing)}"


# ---------------------------------------------------------------------------
# 4. Confidence threshold gating
# ---------------------------------------------------------------------------

def test_nonsense_returns_none(built_artifact, monkeypatch):
    """A genuinely meaningless phrase should not match anything at the
    default threshold; routing falls through to LLM/Markov."""
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()
    r = dictionary_v2.lookup("xyzzy random nonsense plugh frobnicate")
    assert r is None, f"nonsense phrase matched: {r!r}"


def test_high_threshold_may_reject(built_artifact, monkeypatch):
    """At threshold=0.99 even a known phrase may be rejected — this is
    expected and lets the caller dial sensitivity. We tolerate either
    None or a return at or above the threshold."""
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()
    try:
        r = dictionary_v2.lookup("raise the volume", threshold=0.99)
    except TypeError:
        pytest.skip("lookup() does not accept threshold kwarg in this build")
    if r is not None:
        assert r.get("confidence", 0.0) >= 0.99, (
            f"lookup returned below-threshold result: {r!r}"
        )


def test_default_threshold_routes_volume_up(built_artifact, monkeypatch):
    """At the default threshold (~0.7), a clean phrase must route."""
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()
    r = dictionary_v2.lookup("raise the volume")
    assert r is not None, "default-threshold lookup of clean phrase returned None"
    assert "audio.volume_up" in r["handler_type"]


# ---------------------------------------------------------------------------
# 5. No-collision invariant: every phrase resolves to ONE handler
# ---------------------------------------------------------------------------

def test_no_phrase_maps_to_multiple_handlers(built_artifact, monkeypatch):
    """The compiler may legitimately produce overlapping templates, but
    the resolved phrase->handler map must be a function (one handler per
    phrase). If the underlying dict isn't directly inspectable, we skip
    rather than fail."""
    monkeypatch.setenv("AICONTROL_DICTIONARY_V2_PATH", str(built_artifact["path"]))
    _reset_cache()
    # Force load.
    dictionary_v2.lookup("warmup")

    # Try common attribute names for the resolved map.
    table = None
    for attr in ("PHRASES", "_PHRASES", "phrases", "_phrases",
                 "_TABLE", "_table", "DICTIONARY", "_DICTIONARY"):
        cand = getattr(dictionary_v2, attr, None)
        if isinstance(cand, dict) and cand:
            sample = next(iter(cand.values()))
            # Heuristic: handler entries are dicts with handler_type or
            # tuples with a string handler at index 0.
            if isinstance(sample, dict) and "handler_type" in sample:
                table = {k: v["handler_type"] for k, v in cand.items()}
                break
            if isinstance(sample, str):
                table = dict(cand)
                break
            if isinstance(sample, (list, tuple)) and sample \
                    and isinstance(sample[0], str):
                table = {k: v[0] for k, v in cand.items()}
                break

    if table is None:
        pytest.skip(
            "could not introspect resolved phrase table on dictionary_v2"
        )

    # In a function (one handler per phrase) duplicates are impossible by
    # construction since dict keys are unique, so what we really verify is
    # that NO phrase string is associated with multiple handler types
    # (which would only happen if the compiler returned a multimap).
    seen: dict[str, str] = {}
    collisions: list[tuple[str, str, str]] = []
    for phrase, handler in table.items():
        if phrase in seen and seen[phrase] != handler:
            collisions.append((phrase, seen[phrase], handler))
        seen[phrase] = handler

    assert not collisions, (
        f"phrase->handler collisions detected ({len(collisions)}): "
        f"first 5: {collisions[:5]}"
    )
