[Unit]
DefaultDependencies=no
Before=halt.target systemd-halt.service
Conflicts=plymouth-quit.service plymouth-quit-wait.service

[Service]
TimeoutStartSec=10
TimeoutStopSec=10
SuccessExitStatus=0 1

[Install]
WantedBy=halt.target
