#!/bin/bash
# ai-arch/sysctl-tune.sh -- hardware-tiered sysctl application.
#
# Invoked at the tail of /usr/lib/ai-arch/hw-detect.sh once the tier is
# classified.  Writes a SINGLE drop-in file (/run/sysctl.d/90-ai-arch-hw.conf)
# containing tier- and capability-specific values, then triggers
# `sysctl --system` so the kernel re-reads the whole /etc/sysctl.d chain --
# guaranteeing static (50/60/70) AND dynamic (90) values end up consistent.
#
# Why /run and not /etc?
#   - /run is tmpfs: correct values are re-derived every boot even if HW
#     changes (USB-boot moved between machines, VM resized).
#   - /etc is read-only on the live ISO.
#
# Inputs:
#   /run/ai-arch-hw-profile  (PROFILE=OLD|NEW|DEFAULT, plus capability bits)
#   /proc/swaps              (to decide swappiness based on zram presence)
#   /sys/block/*/queue/rotational  (SSD vs HDD dirty ratios)
#
# Output:
#   /run/sysctl.d/90-ai-arch-hw.conf   -- the written tuning
#   stdout log line consumed by systemd journal

set -u
set +e

PROFILE_FILE=/run/ai-arch-hw-profile
OUT_DIR=/run/sysctl.d
OUT_FILE=$OUT_DIR/90-ai-arch-hw.conf

PROFILE=DEFAULT
MEM_MB=0
CPU_CORES=1
ROOT_ROTATIONAL="?"
CPU_HAS_AVX2=0

if [ -r "$PROFILE_FILE" ]; then
    # shellcheck disable=SC1090
    . "$PROFILE_FILE" || true
fi

# --- Probe: is zram active as swap? ----------------------------------------
# zram-generator creates /dev/zram0 and swapons it; if present, we can run
# swappiness high because zstd-compressed RAM swap is effectively free.
HAS_ZRAM=0
if [ -r /proc/swaps ] && grep -q '^/dev/zram' /proc/swaps 2>/dev/null; then
    HAS_ZRAM=1
fi

# --- Probe: any rotational root block device? ------------------------------
# We reuse the hw-detect classification; if unset, re-probe defensively.
if [ "$ROOT_ROTATIONAL" = "?" ] || [ -z "$ROOT_ROTATIONAL" ]; then
    ROOT_ROTATIONAL=0
    for r in /sys/block/*/queue/rotational; do
        [ -r "$r" ] || continue
        if [ "$(cat "$r" 2>/dev/null)" = "1" ]; then
            ROOT_ROTATIONAL=1
            break
        fi
    done
fi

mkdir -p "$OUT_DIR" 2>/dev/null

# --- Begin drop-in ----------------------------------------------------------
{
    echo "# AI Arch Linux -- hardware-tiered sysctl values."
    echo "# Auto-generated by /usr/lib/ai-arch/sysctl-tune.sh at $(date -Iseconds 2>/dev/null || echo unknown)."
    echo "# Profile=${PROFILE}  Mem=${MEM_MB}MB  Cores=${CPU_CORES}  Rotational=${ROOT_ROTATIONAL}  Zram=${HAS_ZRAM}"
    echo "# Overrides: static files in /etc/sysctl.d/ (50/60/70) still apply;"
    echo "# this 90- file wins on conflicts (sysctl last-wins ordering)."
    echo

    # ----- Swappiness -------------------------------------------------------
    # With zram: high swappiness is a WIN -- zstd-in-RAM is faster than
    # re-reading from squashfs / disk for cold pages.  Without zram: low
    # swappiness keeps the desktop snappy.
    echo "# --- Swappiness (zram-aware) ---"
    if [ "$HAS_ZRAM" -eq 1 ]; then
        case "$PROFILE" in
            OLD)  echo "vm.swappiness = 120" ;;   # tiny RAM, lean hard on zram
            NEW)  echo "vm.swappiness = 80"  ;;   # plenty of RAM, but zram is cheap
            *)    echo "vm.swappiness = 100" ;;
        esac
        # vm.watermark_boost_factor -- kick the page-cache reclaim harder
        # when zram is the primary swap (latency-friendly).
        echo "vm.watermark_boost_factor = 0"
        # page-cluster low (0 = 1 page/IO) is best for zram: compressor
        # overhead of a single page is lower than batch.
        echo "vm.page-cluster = 0"
    else
        case "$PROFILE" in
            OLD)  echo "vm.swappiness = 30"  ;;   # slow HDD swap; avoid
            NEW)  echo "vm.swappiness = 10"  ;;   # plenty of RAM, keep hot
            *)    echo "vm.swappiness = 60"  ;;   # kernel default
        esac
        # Larger page-cluster batches disk swap I/O (3 = 8 pages).
        echo "vm.page-cluster = 3"
    fi
    echo

    # ----- VFS cache pressure ----------------------------------------------
    # Lower = kernel keeps dentry/inode cache hot longer.  On OLD HW with
    # slow disk, this means `ls` doesn't re-stat the world.  On NEW HW with
    # NVMe, the difference is nil, but the lower value is still safer.
    echo "# --- VFS cache pressure ---"
    case "$PROFILE" in
        OLD)  echo "vm.vfs_cache_pressure = 50"  ;;
        NEW)  echo "vm.vfs_cache_pressure = 75"  ;;
        *)    echo "vm.vfs_cache_pressure = 100" ;;
    esac
    echo

    # ----- Dirty ratios (SSD vs HDD) ---------------------------------------
    # SSD/NVMe handles small writes well; low dirty_ratio keeps fsync()
    # latency low.  HDD benefits from batched writeback to avoid seek storms.
    echo "# --- Dirty ratios (rotational-aware) ---"
    if [ "$ROOT_ROTATIONAL" = "1" ]; then
        # Spinning disk: batch heavily, pay single fsync penalty once.
        echo "vm.dirty_ratio = 30"
        echo "vm.dirty_background_ratio = 10"
        echo "vm.dirty_expire_centisecs = 6000"
    else
        # SSD / NVMe: low latency + stable tail-latency for compiles & games.
        echo "vm.dirty_ratio = 10"
        echo "vm.dirty_background_ratio = 5"
        echo "vm.dirty_expire_centisecs = 3000"
    fi
    echo

    # ----- min_free_kbytes (low-RAM safety) ---------------------------------
    # 1-2% of RAM as emergency reserve.  Too-low causes alloc failures under
    # pressure; too-high wastes usable memory.  Clamped [32 MiB, 256 MiB].
    echo "# --- Memory headroom ---"
    local_min=$(( MEM_MB * 1024 / 100 ))   # 1% of RAM in KB
    [ $local_min -lt 32768 ] && local_min=32768
    [ $local_min -gt 262144 ] && local_min=262144
    echo "vm.min_free_kbytes = $local_min"
    # extfrag_threshold: favour compaction over reclaim on low-frag systems.
    echo "vm.extfrag_threshold = 500"
    echo

    # ----- Scheduler tweaks (many-core) -------------------------------------
    # migration_cost: cost in ns for migrating a task between CPUs.  Higher
    # = less migration churn.  5 ms on NEW boxes avoids thrash under `make -j`.
    echo "# --- Scheduler (many-core tuning) ---"
    if [ "${CPU_CORES:-1}" -ge 8 ]; then
        echo "kernel.sched_migration_cost_ns = 5000000"
    elif [ "${CPU_CORES:-1}" -ge 4 ]; then
        echo "kernel.sched_migration_cost_ns = 1500000"
    else
        # Default (500000 / 0.5 ms) for 1-2 core old HW -- more migration
        # helps avoid starvation on shallow core count.
        echo "kernel.sched_migration_cost_ns = 500000"
    fi
    # sched_autogroup is already 1 in 50-ai-arch-boot.conf; re-affirm here
    # so a local override can't silently disable desktop fairness.
    echo "kernel.sched_autogroup_enabled = 1"
    echo

    # ----- Network socket buffers (bandwidth × delay product) --------------
    echo "# --- Network buffers (tier-scaled) ---"
    case "$PROFILE" in
        NEW)
            # 16 MiB caps -- enough for 1 Gbit @ 100 ms RTT (BDP=12.5 MiB).
            echo "net.core.rmem_max = 16777216"
            echo "net.core.wmem_max = 16777216"
            echo "net.ipv4.tcp_rmem = 4096 131072 16777216"
            echo "net.ipv4.tcp_wmem = 4096 65536 16777216"
            echo "net.core.netdev_max_backlog = 16384"
            ;;
        OLD)
            # 256 KiB caps -- enough for 100 Mbit @ 20 ms RTT and fits
            # in low-RAM budgets.  Kernel still autotunes WITHIN the window.
            echo "net.core.rmem_max = 262144"
            echo "net.core.wmem_max = 262144"
            echo "net.ipv4.tcp_rmem = 4096 32768 262144"
            echo "net.ipv4.tcp_wmem = 4096 16384 262144"
            echo "net.core.netdev_max_backlog = 1000"
            ;;
        *)
            # 4 MiB caps already set in /etc/sysctl.d/60-network.conf.
            echo "# (DEFAULT) keeping 60-network.conf values: 4 MiB caps"
            ;;
    esac
    echo

    # ----- perf / io_uring / ptrace (NEW HW unlock dev-ergonomics) ---------
    # On NEW HW (assumed personal/developer workstation), we soften a few
    # paranoid defaults so `perf record`, `strace -p`, and io_uring-using
    # applications work without sudo.  These are still tighter than the
    # kernel mainline defaults (which are 0/0/0).
    echo "# --- Dev / profiling unlocks (NEW tier only) ---"
    case "$PROFILE" in
        NEW)
            echo "kernel.perf_event_paranoid = 1"    # allow user-space perf
            echo "kernel.yama.ptrace_scope = 0"      # classic same-uid debug
            # io_uring stays on the kernel default (enabled), overridden
            # only for paranoid profiles below.
            ;;
        OLD)
            # On OLD HW (often public / donated), keep the tight defaults
            # from 70-security.conf.  Also lock io_uring -- kernel-exploit
            # surface, and the RAM cost outweighs the perf win on Pentium 4.
            echo "kernel.perf_event_paranoid = 3"
            echo "kernel.yama.ptrace_scope = 1"
            # Only set io_uring_disabled if the knob exists (Linux >= 6.1).
            if [ -f /proc/sys/kernel/io_uring_disabled ]; then
                echo "kernel.io_uring_disabled = 2"
            fi
            ;;
        *)
            echo "kernel.perf_event_paranoid = 2"    # mainline default
            ;;
    esac
    echo

    # ----- IPC tuning (RAM-aware shmmax clamp) -----------------------------
    echo "# --- IPC limits (RAM-aware) ---"
    if [ "${MEM_MB:-0}" -gt 0 ] && [ "$MEM_MB" -le 1024 ]; then
        # Tiny systems: clamp shmmax to 256 MiB so a runaway allocator
        # can't blow the whole address space.
        echo "kernel.shmmax = 268435456"
        echo "kernel.shmall = 65536"
    elif [ "$MEM_MB" -le 4096 ]; then
        echo "kernel.shmmax = 1073741824"   # 1 GiB
        echo "kernel.shmall = 262144"
    else
        # Keep the 8 GiB default from 50-ai-arch-boot.conf.
        echo "# (>=4 GiB RAM) using 50-ai-arch-boot.conf default: shmmax=8 GiB"
    fi
    echo

    # ----- TFO / mtu_probing toggles (OLD HW -> conservative) --------------
    # Fast-open + MTU probing help modern networks; on ancient kernels they
    # can trip buggy middleboxes.  Keep mainline on NEW/DEFAULT, back off OLD.
    echo "# --- Connection-setup tuning ---"
    case "$PROFILE" in
        OLD)
            echo "net.ipv4.tcp_fastopen = 1"        # client-only
            echo "net.ipv4.tcp_mtu_probing = 0"     # avoid middlebox breaks
            ;;
        *)
            # Static 60-network.conf already set 3 / 1 -- don't overwrite.
            :
            ;;
    esac
} > "$OUT_FILE" 2>/dev/null

# --- Apply ------------------------------------------------------------------
# `sysctl --system` re-reads ALL drop-ins in order; safer than setting each
# value individually because we pick up the static files AND our 90- on a
# single pass.  Failures are non-fatal.
if command -v sysctl >/dev/null 2>&1; then
    sysctl --system >/dev/null 2>&1 || sysctl -p "$OUT_FILE" >/dev/null 2>&1 || true
fi

echo "ai-sysctl-tune: wrote $OUT_FILE (profile=$PROFILE zram=$HAS_ZRAM rot=$ROOT_ROTATIONAL)"
exit 0
